variables:
  DOCKER_DRIVER: overlay

build:gcp:
  needs: ["jest-server"]
  extends:
    - .default-ubuntu
    - .auth-gcp
    - .filter:rules:build-image-gcp
  stage: build
  script:
    - gcloud auth configure-docker
    - docker build -t $GCP_IMAGE ./server --build-arg INTERNAL_PACKAGES_GITLAB=$INTERNAL_PACKAGES_GITLAB
    - docker push $GCP_IMAGE
